alias: Turn on phone charger
description: ''
trigger:
  - below: 50
    device_id: 0bade40460214b3b91f7a531661a5d46
    domain: sensor
    entity_id: sensor.mi_note_10_lite_battery_level
    platform: device
    type: battery_level
condition:
  - condition: device
    device_id: 0bade40460214b3b91f7a531661a5d46
    domain: device_tracker
    entity_id: device_tracker.mi_note_10_lite
    type: is_home
  - condition: state
    entity_id: sensor.mi_note_10_lite_battery_state
    state: discharging
action:
  - device_id: fc1aef35dfca459799e9ab15a448e5b7
    domain: switch
    entity_id: switch.smart_plug_phone_birgit
    type: turn_on
mode: single
initial_state: true

